name: Deploy App Service Python

on:
  #push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: false
        type: choice
        options:
        - dev
        - stag
        - prod
        default: 'dev'
env:
  ACTIONS_RUNNER_DEBUG: true
  ARM_USE_OIDC: true
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  APP_SERVICE_NAME: 'web-gh-oidc-demo'
  RESOURCE_GROUP_NAME: 'rg-gh-oidc-demo'
  ZIP_FILE_NAME: 'app.zip'

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: [self-hosted, python]
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Get packages
        run: |
            cd quickstart_python
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - name: Zip the code
        run: |
            cd quickstart_python
            zip -r ${{ env.ZIP_FILE_NAME }} .

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ env.ARM_CLIENT_ID }}
            tenant-id: ${{ env.ARM_TENANT_ID }}
            subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
    
      - name: Deploy Pub Function                
        run: |
            az webapp deploy \
                --name  ${{ env.APP_SERVICE_NAME }} \
                --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
                --src-path quickstart_python/${{ env.ZIP_FILE_NAME }}
